//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CeritaKita.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class reply
    {
        public string id { get; set; }
        public string parentId { get; set; }
        public string isiPost { get; set; }
        public int like_ { get; set; }
        public int dislike { get; set; }
        public string thread { get; set; }
    
        public virtual post post { get; set; }
    }
}
